### ISSUE TITLE
PA Review: Lists and cards

### ISSUE THREAD

**Issue by roblim** [roblim/kardboard#12]

**Comment by LochandQuay** [comment]
@roblim 

Cards & Lists look pretty good. However, to be a functional Trello clone, you need to be able to move cards between lists and _ideally_ reposition lists and cards on a list. We usually recommend that you use a React Drag'n'Drop package for this. However, the minimum would be something like a `Move Card` button on the modal that gives you a list of the other lists that you can move the card to.

**Comment by roblim** [comment]
@LochandQuay - done.

**Comment by roblim** [comment]
@LochandQuay 
Just a heads up - changed project name. New heroku url: https://kardboard-io.herokuapp.com/#/
