### ISSUE TITLE
PA Review: Boards

### ISSUE THREAD

**Issue by roblim** [roblim/kardboard#13]

**Comment by roblim** [comment]
@LochandQuay 
demo user: 
email: y.kusama@art.jp
password: password

**Comment by LochandQuay** [comment]
@roblim Is this ready for review? I can't create a board or anything. Index looks nice though!

**Comment by roblim** [comment]
@LochandQuay - board create/modal functionality pushed to heroku now.

**Comment by LochandQuay** [comment]
@roblim 

- Getting `500 Internal Server Error`s when trying to fetch/create boards from my account.

You may have forgotten to fully migrate something?

**Comment by roblim** [comment]
@LochandQuay . Sorry about that. Works in development and everything is pushed to Heroku. Rebuilt/seeded production database too. Any ideas why it wouldn't work on production? Is there a config thing somewhere I should check out?

**Comment by LochandQuay** [comment]
@roblim Whatever you did fixed it. It's usually a migration that wasn't run. 

- Could use a little more styling on the new board form. Would actually prefer if it was just a modal that went directly over the new board button so it looked like it does on Trello (where the button turns into the new board form). 
- Show page for board should have the name of the board somewhere.

Major thing that everyone needs to do at some point but is particularly important for a project like yours where each individual should only be able to see their own stuff:
- You need to clear your entire store on logout. Basically, I can log into my own account, log out, and then log into the Demo account and still see my boards. There are a few ways you can handle this.

**Comment by roblim** [comment]
@LochandQuay - complete
