### ISSUE TITLE
PA Review: New account creation and login

### ISSUE THREAD

**Issue by roblim** [roblim/kardboard#9]

**Comment by roblim** [comment]
@LochandQuay 
demo user: 
email: y.kusama@art.jp
password: password

**Comment by LochandQuay** [comment]
@roblim 

Almost there! A few small things.

General: 
- Should clear errors when switching between forms
- Demo login should exist as a button on both forms so recruiters can easily access a pre-fleshed out account. 


Styling: 
- Errors need more whitespace above them (are really really close to the "Please sign up or log in" part)
- logout button needs more styling
- buttons should do something different on hover (pointer change, background color change or other styling change)

**Comment by roblim** [comment]
Complete. @LochandQuay
